### ISSUE TITLE
[ENG-172] Create react hook for new publication

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#2131]
<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-172](https://linear.app/heyxyz/issue/ENG-172)</sub>

**Comment by hellskater** [comment]
Hey can you tell me more about this?

**Comment by bigint** [comment]
@hellskater if you check `NewPublication.tsx` component it is cluttered with tons of code, we need to migrate the code to a hook for creating a publication

**Comment by nicefacer** [comment]
Can I take up this if nobody is on it, @bigint ?
