### ISSUE TITLE
Add synpress plugin for web3 testing in playwright

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#2170]
In order to improve the testing capabilities of our application, we would like to integrate the Synpress plugin for Playwright. This will allow us to perform wallet signing and test authenticated sessions more efficiently, ensuring a more robust and secure application.

## Requirements

- Install and set up the Synpress plugin for Playwright in the project
- Configure the Synpress plugin to work with our current testing environment
- Implement wallet signing functionality to allow testing of blockchain transactions
- Create tests to verify the functionality of authenticated sessions within the application

## Acceptance Criteria

- Synpress plugin is installed and configured in the project
- Wallet signing functionality is implemented and working as expected
- Authenticated session tests are created and passing

## Additional Context

Synpress is a plugin for Playwright that provides an easy way to test Ethereum dApps. It includes features such as wallet signing, key management, and contract interaction. Integrating this plugin will help us streamline the testing process for our blockchain-based application, as well as improve the overall security and robustness of the platform.

https://github.com/drptbl/synpress-examples/blob/master/playwright/isolated-state/tests/connect-wallet.spec.ts

https://github.com/Synthetixio/synpress

**Comment by benbaessler** [comment]
@bigint I'd be interested in working on this issue. Can you provide some more details like which tests should be included?

**Comment by bigint** [comment]
@benbaessler We need to write test cases for authenticated users, like we need to mock user signing and do e2e there.

**Comment by Seroxdesign** [comment]
@bigint is this assigned or can I get to working on it?

**Comment by bigint** [comment]
@Seroxdesign I'll assign to you 🙇🏼

**Comment by Seroxdesign** [comment]
Talking some people people from Synpress, they're helping me debug this issue
