### ISSUE TITLE
Add location selection from google maps API dropdown

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#2347]
https://github.com/lensterxyz/lenster/assets/69431456/b2e16352-fa6f-429d-83be-9f7db98b621c

<sub>[ENG-63](https://linear.app/heyxyz/issue/ENG-63/add-location-selection-from-google-maps-api-dropdown)</sub>

**Comment by 5war00p** [comment]
@bigint  Can I take this up?

**Comment by bigint** [comment]
@5war00p sure you can take this!

**Comment by 5war00p** [comment]
And where exactly did you want to add locations? Is it in global search?

**Comment by 5war00p** [comment]
> @bigint And where exactly did you want to add locations? Is it in global search?

@bigint  can you answer this? will start working on it asap.

**Comment by MuhmdAjeer** [comment]
@bigint is this issue still open?.if it is can you assign this to me.

**Comment by ishqDehlvi** [comment]
@bigint How can I replicate this issue??

**Comment by ancxanas** [comment]
I am seeing 4 attempts with no solution. Does it mean they abandoned it?

**Comment by akhiltej-2514** [comment]
@bigint adding where in the home page? along with users?

**Comment by bigint** [comment]
It is needed in profile settings page!

**Comment by guptadeepak8** [comment]
@bigint This issue requires Google Maps API.

**Comment by aadarsh-nagrath** [comment]
@bigint is this issue still open? if it is can you assign this to me

**Comment by aadarsh-nagrath** [comment]
@bigint added working video ✅
