### ISSUE TITLE
[ENG-42] About the display bug of mirror

### ISSUE THREAD

**Issue by hbue666** [heyxyz/hey#2510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user tries to mirror, it needs to sign twice in the wallet, the first signature mirror is counted once, displayed as mirror 1; when the user confirms the gas payment for the second time, it is counted again, displayed as mirror 2, that is, when the user mirrors will be repeated. But when the user checks the details of the post, it returns to normal and the number of mirrors is 1

https://user-images.githubusercontent.com/85141427/231413261-910c3486-dfa1-4754-945a-01079380b153.mp4

### Expected Behavior

I want to be able to display the number of mirrors correctly on the fly

### Steps To Reproduce

https://user-images.githubusercontent.com/85141427/231414633-78fc8d4e-e0d6-4f01-a766-3d38ef364bc6.mp4

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome, Firefox, Edge

<sub>[ENG-42](https://linear.app/heyxyz/issue/ENG-42/about-the-display-bug-of-mirror)</sub>

**Comment by saagu335** [comment]
Thanks for raising, we will check this and fix it ASAP 🙇
