### ISSUE TITLE
Threads should scroll down to the given post

### ISSUE THREAD

**Issue by saagu335** [heyxyz/hey#2555]
When opening a thread it should open the main post first and threads above

Eg: https://lenster.xyz/posts/0x06-0x0188

It should open the page like this

![Image](https://github.com/lensterxyz/lenster/assets/69431456/eec1031a-1a63-48cd-8af0-be90ec4d788b)

And not like this

![Image](https://github.com/lensterxyz/lenster/assets/69431456/74a54a0f-4504-40f5-8681-9dfd5faf17f5)

<sub>[ENG-43](https://linear.app/heyxyz/issue/ENG-43/threads-are-not-properly-shown)</sub>

**Comment by foolo** [comment]
For anyone picking this, see https://github.com/heyxyz/hey/pull/3812#issuecomment-1748167836

Suggested solution is to load the main publication first, and then lazy load the parent publications when scrolling

**Comment by vijayraghav-io** [comment]
Hi @foolo , I am working on this you can assign to me

**Comment by nitinshr135** [comment]
@foolo can you assign this task to me?

**Comment by foolo** [comment]
> @foolo can you assign this task to me?

@nitinshr135 Done!

**Comment by SSHari** [comment]
I thought I'd try my hand at this too /attempt #2555

**Comment by nitinshr135** [comment]
raising my PR in a few hours as well. do check my approach as well @foolo :D

**Comment by MuhmdAjeer** [comment]
is this issue still open?
can i work on this please?

**Comment by rishi-raj-jain** [comment]
@bigint this is fixed, right?
