### ISSUE TITLE
[ENG-53] Display overflow on long usernames

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#2684]
### Current Behavior

Long usernames overflow the user menu:

![Screenshot_2023-04-24_13-59-18](https://user-images.githubusercontent.com/667227/233989917-dc02f339-2900-4642-b56e-ddbac820acac.png)

### Expected Behavior

For example, show a wider menu, or truncate the userame with "…"

### Steps To Reproduce

(Most convenient to reproduce it on testnet, since registration is gated on mainnet)

- Create a user with a long username (for example "veryverylonglensterusernb")
- Login and click the user menu.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

<sub>[ENG-53](https://linear.app/heyxyz/issue/ENG-53/display-overflow-on-long-usernames)</sub>

**Comment by progmatic-99** [comment]
Can i work on this??

**Comment by foolo** [comment]
> Can i work on this??

@progmatic-99 Go ahead! Also see https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md if you haven't yet

**Comment by progmatic-99** [comment]
@foolo @bigint I had a question regarding sign up. Suppose I want to make different accounts on the same wallet, is this possible?
Also, is there any communication channel for asking my doubts relating to development on lenster??

**Comment by bigint** [comment]
@progmatic-99 you can create here https://testnet.lenster.xyz/new/profile

**Comment by foolo** [comment]
@bigint This one turned out to be a bit tricky, because CSS ellipsis doesn't work with text gradient, (if we add an ellipsis with `text-overflow: ellipsis;` it will be hidden by `bg-clip-text text-transparent`, which is used for the color gradient in `<Slug>`.)
Some possible options:
- just make the login menu wider
- truncate, but don't show an ellipsis
- don't use color gradient text style for the username

**Comment by bigint** [comment]
Fixed
