### ISSUE TITLE
[ENG-55] Add DMs search

### ISSUE THREAD

**Issue by saagu335** [heyxyz/hey#2743]
null

<sub>[ENG-55](https://linear.app/heyxyz/issue/ENG-55/add-dms-search)</sub>

**Comment by kesh-007** [comment]
@bigint  is the issue still open? I am interested in working on that

**Comment by skyrunner360** [comment]
> @bigint is the issue still open? I am interested in working on that

@bigint I'd also like to work on this, please let me know if it's still open. @kesh-007 maybe we can work together?
