### ISSUE TITLE
Add progressive loading of images from blur to bright

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3067]
null

<sub>[ENG-12](https://linear.app/heyxyz/issue/ENG-12/add-progressive-loading-of-images-from-blur-to-bright)</sub>

**Comment by theonlyjunaid** [comment]
/attempt #3067  I can take this up I did this before, please assign me

**Comment by Nirali-Ahir** [comment]
Hey @bigint and @foolo, I'm halfway through. I wanted to ask do we have low-resolution thumbnail images available from ImageKit ? Or should I use a static placeholder image while the main image is loading?

**Comment by theonlyjunaid** [comment]
> > @Nirali-Ahir i can help in getting imagekit low resolution image can we do it together. @bigint @foolo i just want to confirm that are you using imagekit by default or not because some images are not on imagekit
> 
> mine almost done just nned to asign prop

You can refer https://docs.imagekit.io/features/image-optimization/quality-optimization for getting the image of custom quality without changing in dimensions of image

**Comment by theonlyjunaid** [comment]
> @theonlyjunaid @Nirali-Ahir I don't know if the super-low-res images are readily aviable on ImageKit, but yes, we should use Imakekit. So maybe it need to be configured to generate mini thumbnails.
> 
> in the Linear issue, @bigint wrote the following:
> 
> > we can use imagekit to reduce image size to 5px x 5px to load the initial image and load the big image next to that

imagekit provides options for custom quality that we can use according to our need in which quality can range from 1-100.
image with quality 1 has almost 10 times smaller size compared to the image with quality 100

**Comment by Nirali-Ahir** [comment]
https://github.com/heyxyz/hey/assets/144760374/4736e944-8ec1-48b8-ad64-3826f822e134

**Comment by hamzaahmadaslam** [comment]
Hey can i start this one?

**Comment by bigint** [comment]
@hamzaahmadaslam go through the above convos!

**Comment by Rutik7066** [comment]
hey @bigint I have experienced with blur to  bright image loading. May get assigned this one or should start working on it directly?

**Comment by bigint** [comment]
No longer needed!
