### ISSUE TITLE
Fix spotify.link rich oembed

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3207]
https://lenster.xyz/posts/0x73b1-0x2a23

<sub>[ENG-14](https://linear.app/heyxyz/issue/ENG-14/fix-spotifylink-rich-oembed)</sub>

**Comment by fvckDesa** [comment]
@bigint can you give me more info of the bug and the expected result?

**Comment by prateekkalra** [comment]
Hey @bigint 
Could you please provide some details regarding the issue?
Thanks!

**Comment by rishi-raj-jain** [comment]
@bigint

Is this open to new attempts?

**Comment by itsmerachit** [comment]
@bigint Is this issue fixed or still open?
