### ISSUE TITLE
Create post: tagging users misbehaves when there's "." right after the handle

### ISSUE THREAD

**Issue by random-potential** [heyxyz/hey#3385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a post and tagging another user, if there's a "." right after the lens handle (e.g.: "Take a look at that @user.lens."), the "." is treated as a part of the handle and included in the hyperlink. As a result:
- That link leads to 404
- Tagged user is not displayed in the right sidebar of the post
- Possibly, that user is not tagged properly and is not notified (didn't check)

### Expected Behavior

The "." at the end of the handle should be treated as text.

### Steps To Reproduce

Open create post dialog. Tag any user and leave dot right after it in format of "@handle.lens." Save post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![image](https://github.com/lensterxyz/lenster/assets/140802576/e33ef2b0-00f9-45e8-aa4b-cf575e22e91d)

**Comment by bigint** [comment]
Should be fixed
