### ISSUE TITLE
[ENG-15] Duplication of profiles while changing profile 

### ISSUE THREAD

**Issue by DanIsNearby** [heyxyz/hey#3419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The handles are dobbled each time the account is changed 

![image](https://github.com/lensterxyz/lenster/assets/91475837/5dd9b30b-3b05-4ad8-8efd-263fd4060ac7)

### Expected Behavior

Handles are displayed only once 

![image](https://github.com/lensterxyz/lenster/assets/91475837/68cb7c62-5975-4a38-9932-a960bbe5c4e7)

### Steps To Reproduce

switch profile in the switch profile option 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

<sub>[ENG-15](https://linear.app/heyxyz/issue/ENG-15/duplication-of-profiles-while-changing-profile)</sub>

**Comment by bigint** [comment]
fixed
