### ISSUE TITLE
Support link in publication that don't have http or https

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3490]
https://lenster.xyz/posts/0x01d7ea-0x02

<sub>[ENG-18](https://linear.app/heyxyz/issue/ENG-18/support-link-in-publication-that-dont-have-http-or-https)</sub>

**Comment by foolo** [comment]
@bigint Should this apply for oembed url detection too?

**Comment by foolo** [comment]
Right now we are using a regex, which only detects URLs that starts with http or https. The benefit is that we don't get many false positives, but the drawback is that we don't detect e.g. `example.com`.
If we change to detecting anything that looks like aaaaa.bbb with just a regex, we would get quite many false positives for example when a user omits a space, such as  "i went to the gym.now i'm tired", would give the URL `gym.now`. To get fewer false positives, we would probably need a more intelligent function, list of TLDs, etc, and not just a regex.
@bigint Would these false positives be OK? Or should we go for a more advanced solution, for example using a URL detection library?
