### ISSUE TITLE
[ENG-22] Messages in Inbox not showing on first load

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inbox is displayed as empty until you first switch to Following and then back to Inbox again. See screencast.

https://github.com/lensterxyz/lenster/assets/667227/1f5fa761-684f-4959-8e9a-0df6d23ba7de

### Expected Behavior

Should show the messages in Inbox at first load of /messages

### Steps To Reproduce

Go to https://lenster.xyz/messages
Observe empty inbox
Switch to Following
Switch back to Inbox

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

<sub>[ENG-22](https://linear.app/heyxyz/issue/ENG-22/messages-in-inbox-not-showing-on-first-load)</sub>

**Comment by bigint** [comment]
@bhavya2611 do you have any ideas?

**Comment by Kmarxalpha1** [comment]
I think more upgrades are needed
