### ISSUE TITLE
[ENG-25] Infinite repeating NFTs in curator dialog

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

Using a profile that does not yet have a curated NFT collection:
- Go to your profile > NFTs > Get started
- Scroll though the list of NFTs

### Current Behavior

Scrolls infinitely with the same NFTs repeated

https://github.com/lensterxyz/lenster/assets/667227/c4202a68-4c26-41a6-9069-e0fce2500aba

### Expected Behavior

Scrolling should stop when all NFTs have been rendered

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

<sub>[ENG-25](https://linear.app/heyxyz/issue/ENG-25/infinite-repeating-nfts-in-curator-dialog)</sub>

**Comment by bigint** [comment]
Is this a api issue?
