### ISSUE TITLE
Notification show when you comment on your own posts

### ISSUE THREAD

**Issue by random-potential** [heyxyz/hey#3705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If user comments on their own post or tags themselves somewhere else, in Notifications page, a notification will be displayed about that action.

### Expected Behavior

Users own actions should not be displayed in Notifications page. 

### Steps To Reproduce

Comment on your own post, or tag yourself in some other post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

Example:
Comment on own post: https://lenster.xyz/posts/0xe30c-0x9e-DA-3a943e41
User's Notifications page:
![image](https://github.com/lensterxyz/lenster/assets/140802576/e3184811-553f-4b9f-949e-95b865f88f01)

**Comment by marvelxcodes** [comment]
I am interested to work in this issue. Can I get it assigned?
