### ISSUE TITLE
Adding a poll to the post resets Collect settings of that post 

### ISSUE THREAD

**Issue by random-potential** [heyxyz/hey#3707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Open new post dialog.
Add Collect settings (e.g., make post collectable).
Add a poll.
Publish the post.
Open the post to view it: there's no option to collect the post.

### Expected Behavior

Adding a specific post setting should not override/reset other post settings, unless there are reasons for it. 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Should be fixed
