### ISSUE TITLE
[ENG-10] Text is overlapping

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#3745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text publications with a larger amount of text on Lenster are overlapping on mobile browsers. I've tested Safari, Brave, and Zerion's built-in browsers, but none of them display the textual data without overlapping.

![IMG_6206](https://github.com/lensterxyz/lenster/assets/19304661/8fff68b9-85cb-46fc-841a-5948dbbeb2f4)
![IMG_6207](https://github.com/lensterxyz/lenster/assets/19304661/b3251a44-b4fa-4c19-b267-761bbd199f41)

### Expected Behavior

Text lines should be displayed one below the other, without being grouped or overlapping.

### Steps To Reproduce

Open Lenster on any of the mentioned mobile browsers, and you should encounter the issue. While I haven't tested it on Chrome or other mobile browsers, I would assume that the behavior is the same.
I'm using an iPhone 13 Pro Max with iOS 16.6.0.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

### Anything else?

**What browser(s) does this occur on?**
 - Every mobile browser I've tried.

I've noticed that there was a previous report for this issue, but it was marked as resolved. However, the issue has returned. Here's the link to the closed report: https://github.com/lensterxyz/lenster/issues/1922"

<sub>[ENG-10](https://linear.app/heyxyz/issue/ENG-10/text-is-overlapping)</sub>

**Comment by foolo** [comment]
https://lenster.xyz/posts/0x02-0x5b-DA-eaec8ab9

**Comment by aurosevic** [comment]
> https://lenster.xyz/posts/0x02-0x5b-DA-eaec8ab9

So apparently when you're viewing the post directly on its link everything seems as it should. Those overlapping problems are visible on previews in a home feed, recommended feed, on profile pages, and so on. That's what I've found out so far. You can open any profile with posts longer than a few lines and it's going to be visible. Looks pretty bad when reading the posts from the home page or someone's profile.

**Comment by foolo** [comment]
@aurosevic Thanks for clarifying! Hmm, I checked on my phone and also in mobile-mode on browser, but i still can't reproduce it. For example, this is how it looks on my phone, when viewing the post as appearing in aaveaave's profile feed:
![2023-09-12 07 16 08](https://github.com/lensterxyz/lenster/assets/667227/c055e063-ee22-41c7-a4ee-07e15cce5fe0)

**Comment by bigint** [comment]
I guess happening only on iOS, i see the issue too!

**Comment by aurosevic** [comment]
Looks like it. I've tried on couple iOS devices, and they all suffer the same issue.

**Comment by adithyaakrishna** [comment]
Hey @Vishal-Sikka 
Could you pls lmk if you are working on this? If not would love to take this up :)

**Comment by Vishal-Sikka** [comment]
i am working
