### ISSUE TITLE
[ENG-159] Language popup shown off-screen

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the language selector is in the lower part of the screen, the menu pops up partly or entirely outside the browser screen

### Expected Behavior

The whole popup menu should be visible

### Steps To Reproduce

Click the language selector when it is in the lower part of the screen

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

https://github.com/lensterxyz/lenster/assets/667227/1398d7ea-d14b-421a-bfb4-093575560419

<sub>[ENG-159](https://linear.app/heyxyz/issue/ENG-159)</sub>

**Comment by MAYANK-TRIPATH** [comment]
I guess just adding `style={{ transform: 'translateY(-100%)' }}` in `<Menu.Items` will resolve the problem

**Comment by bigint** [comment]
We removed lingui in lens v2, we will pick this again when migrating to app router v2

closing this now!

**Comment by bigint** [comment]
cool
