### ISSUE TITLE
[ENG-255] Pictures are not showing

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#3795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some of the pictures uploaded in posts are not displaying in either the post preview or when I click on the picture to open it. 

Here are two posts with this issue:
* https://lenster.xyz/posts/0x01d622-0x09
* https://lenster.xyz/posts/0x01d622-0x08

This issue occurs on both mobile and desktop platforms(Chrome, Brave, Safari). On Firefox the infura-ipfs link is written on top of the placeholders for the images that are missing. 

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Brave, Safari

<sub>[ENG-255](https://linear.app/heyxyz/issue/ENG-255)</sub>

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by aurosevic** [comment]
Hey, thanks for answering. Could you report this issue to the backend team?
