### ISSUE TITLE
[ENG-257] Cooldown logic

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On https://lenster.xyz/settings/danger
the text says "A 7-day Security Cooldown Period need to be elapsed for the Profile Guardian to become effectively disabled."
But then, the time seems to actually be 5 minutes, and not 7 days.

![Screenshot_2023-09-18_17-28-01](https://github.com/lensterxyz/lenster/assets/667227/af26bc14-fbef-49f7-8bb9-4f9aa0b4188c)

![Screenshot_2023-09-18_17-36-26](https://github.com/lensterxyz/lenster/assets/667227/f961f263-8c4b-4d47-84f7-c419b7e5c049)

### Expected Behavior

Value in message should match the actual value used

### Steps To Reproduce

- Go to https://lenster.xyz/settings/danger > Disable profile guardian
- Observe the message
- Click **Disable now**
- Refresh page
- Observe the cooldown time

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

there is also some very strange logic in apps/web/src/components/Shared/ProtectProfile.tsx

```
  const coolOffDate =
    profileGuardianInformation.disablingProtectionTimestamp as any;
  const coolOffTime = new Date(
    new Date(coolOffDate).getTime() + 5 * 60 * 100
  ).toISOString();
  const isCoolOffPassed = new Date(coolOffDate).getTime() < Date.now();
```
The disablingProtectionTimestamp seems to come from the API and already contain the 5 additional minutes.
Then we do some math (`new Date(coolOffDate).getTime() + 5 * 60 * 100`) which is very strange, because getTime() returns milliseconds, so if anything, it should multiply by 1000. The effect is that it adds 30 seconds (one tenth of 5 minutes), so the resulting cooldown is 5m 30s. Although, this logic is superfluous anyway, since the 5 minutes are already included in disablingProtectionTimestamp.

<sub>[ENG-257](https://linear.app/heyxyz/issue/ENG-257)</sub>

**Comment by KshitijBharde** [comment]
Hi @bigint, can I take up this issue, I came looking for issues to solve for hacktoberfest and loved the idea of decentralized social media, if there are any other issues as well I would like to contribute.
