### ISSUE TITLE
[ENG-253] Empty i18n commits

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Empty lines are added and removed again in a lot of successive commits, which makes it hard to view history

For example, these commits come in sequence with nothing in between, and only contain empty lines:
https://github.com/lensterxyz/lenster/commit/b304f50e9d7c2fe333a7b645e7c0f51259c30e61
https://github.com/lensterxyz/lenster/commit/7d1b09f16ad073613c60c7cb73f271a707ffa1b2
https://github.com/lensterxyz/lenster/commit/4aab4e98b1f1c8c065f63b8654de11a42dca5032
https://github.com/lensterxyz/lenster/commit/ebfdbb4e9e153dd6e092518ff1a5e80d4d5f3530
https://github.com/lensterxyz/lenster/commit/74c743e06a69dfb495924c5217c63be754ba61d9

![Screenshot_2023-09-19_15-01-12 (copy 1)](https://github.com/lensterxyz/lenster/assets/667227/874acccc-a710-430a-b500-9e7925510e87)

### Expected Behavior

Ideally, I18n commits should not be committed if they don't have any new content

### Steps To Reproduce

Observe git history, for example the commits up to and including b304f50e9d7c2fe333a7b645e7c0f51259c30e61

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Others

<sub>[ENG-253](https://linear.app/heyxyz/issue/ENG-253)</sub>

**Comment by utsav00** [comment]
Hey @foolo, what do you have in mind for this? I'm thinking sine crowdin now adds a new line at the end of file everytime, should we add a new line check rule in eslint config and `locales` folder check to the linter, so it throws an error if someone removes it mistakenly?
Let me know what your thoughts are.

PS - Not working on this issue (but can if there's a clear approach and no one to pick it up) but just wanted to see listen to your ideas since I use crowdin as well for a different project.

**Comment by foolo** [comment]
@utsav00 Ah, I hadn't investigated it much, but now I can see that as you say, it's the last line of the po files, that is added and removed again. So it seems like 
https://github.com/heyxyz/hey/blob/main/.github/workflows/crowdin-download.yml
adds the newlines, and https://github.com/heyxyz/hey/blob/main/.github/workflows/i18n-extract.yml
removes them again.
So my first idea would be to make sure that i18n-extract.yml doesn't remove the newlines (a properly formatted text file should have a newline at the end in my opinion.)

Although, there is already a PR open for this issue, but that PR probably need to be changed, https://github.com/heyxyz/hey/pull/3858

**Comment by aayushchugh** [comment]
is this fixed yet?

**Comment by ologbonowiwi** [comment]
Is this still open @bigint? I don't see crowdin or i18n-extract workflows anymore.
