### ISSUE TITLE
[ENG-265] Translate text isn't formatted correctly

### ISSUE THREAD

**Issue by nnisarggada** [heyxyz/hey#3859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The translate text contains text like '%20' instead of spaces.

### Expected Behavior

The translate text should be formatted correctly, having spaces. 

### Steps To Reproduce

Translate any post

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

### Anything else?

![2023-10-02_19-54](https://github.com/heyxyz/hey/assets/70348851/2a96bd1a-bf0d-42f8-b33a-e92bb9a3bf13)

<sub>[ENG-265](https://linear.app/heyxyz/issue/ENG-265)</sub>

**Comment by ologbonowiwi** [comment]
likely calls [decodeURI](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) with the string will fix it.
