### ISSUE TITLE
[ENG-269] Migrate from pnpm to bun

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3870]
Migrate from pnpm to bun, make sure it works on gh actions and vercel

<sub>[ENG-269](https://linear.app/heyxyz/issue/ENG-269)</sub>

**Comment by rishi-raj-jain** [comment]
I'd not recommend Bun for workspaces. It's just not stable there right now.

**Comment by rishi-raj-jain** [comment]
I know nobody asked but I have worked for a PR for Lenster back in the day.

**Comment by bigint** [comment]
Not gonna do this 🙇🏼, bun dont have much support with monorepo

**Comment by gouravmpk** [comment]
ahh okay
