### ISSUE TITLE
can't change cover

### ISSUE THREAD

**Issue by zloijopa** [heyxyz/hey#3879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am uploading cover, saving, get a message that it was successful and then no cover.
<img width="809" alt="Screenshot 2023-10-04 at 23 37 14" src="https://github.com/heyxyz/hey/assets/147005556/c7397f87-de3c-42a0-bd2b-f8fa3537dded">
<img width="1282" alt="Screenshot 2023-10-04 at 23 37 36" src="https://github.com/heyxyz/hey/assets/147005556/1bf4e71d-4d50-473d-a144-41e3affd3f0a">

### Expected Behavior

I want this cover be there after I uploaded this :)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
It will take some time to index 🙇🏼
