### ISSUE TITLE
Link to DMs are not working

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3883]
<img width="419" alt="image" src="https://github.com/heyxyz/hey/assets/69431456/12b600eb-1f05-4185-85a2-5d4f8c0cd4b5">

<sub>[ENG-270](https://linear.app/heyxyz/issue/ENG-270)</sub>

**Comment by evoxf1** [comment]
Will anyone assign this or we start working?

**Comment by vivekchavan14** [comment]
> Will anyone assign this or we start working?

u should fork and fix it , no one will assign u

**Comment by evoxf1** [comment]
> > Will anyone assign this or we start working?
> 
> u should fork and fix it , no one will assign u

thats odd

**Comment by vivekchavan14** [comment]
> > > Will anyone assign this or we start working?
> > 
> > 
> > u should fork and fix it , no one will assign u
> 
> thats odd

i did not get u

**Comment by bigint** [comment]
**Created a Height ticket**

https://hey.height.app/inbox/T-649

**Comment by bigint** [comment]
**Created a Height ticket ✨**

https://hey.height.app/T-649

**Comment by petermdenton** [comment]
Still seeing the bug on my end.
