### ISSUE TITLE
limit

### ISSUE THREAD

**Issue by Aramesh1977** [heyxyz/hey#3916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, unfortunately, my account has been limited for about five months. Please fix it. I am unable to continue working

### Expected Behavior

Hello, unfortunately, my account has been limited for about five months. Please fix it. I am unable to continue working

### Steps To Reproduce

Hello, unfortunately, my account has been limited for about five months. Please fix it. I am unable to continue working

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Hello, unfortunately, my account has been limited for about five months. Please fix it. I am unable to continue working

**Comment by Aramesh1977** [comment]
Unfortunately, my account has been limited for five months and cannot be fixed. Please check my account https://hey.xyz/u/esi56

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
