### ISSUE TITLE
Incorrect detection of URL with semicolon

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

Create a post with an URL that contains a semicolon, for example:
```https://bitcointalk.org/index.php?action=profile;u=3```

### Current Behavior

Only a part of the URL is detected. See screenshots.

### Expected Behavior

The whole URL should be detected

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

**Composing:**

![Screenshot_2023-10-23_19-41-52](https://github.com/heyxyz/hey/assets/667227/abd9baa8-62bf-439f-8b78-5a2a7850e9bc)

**Rendered:**

![Screenshot_2023-10-23_19-42-23](https://github.com/heyxyz/hey/assets/667227/876d902c-3e2e-4c04-b1e9-55b34b6944a7)

**Comment by joberthrogers18** [comment]
@foolo can I get this issue?

**Comment by foolo** [comment]
@joberthrogers18 go ahead!
