### ISSUE TITLE
Upload of image causes the Post Modal to disappear 

### ISSUE THREAD

**Issue by 0x4Graham** [heyxyz/hey#3939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I upload an image to the "Post" modal, the post modal disappears and a grey background is displayed. 

### Expected Behavior

Once image uploaded I can complete text for Post and then post it, 

### Steps To Reproduce

Create Post
Upload image
Post modal disappears 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by vinaybadgujar102** [comment]
Hey @bigint, I can work on it
