### ISSUE TITLE
Youtube issues with embed on mobile 

### ISSUE THREAD

**Issue by DanIsNearby** [heyxyz/hey#3949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Youtube embed does not scale correctly

### Expected Behavior

Youtube should scale correctly

### Steps To Reproduce

Visit a post with youtube video on mobile

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

### Anything else?

Video of behavior https://hey.xyz/posts/0x0182d8-0x0126

**Comment by Jaimin25** [comment]
If this is still a problem, I have a solution and work on it
https://github.com/heyxyz/hey/assets/65119631/94ebaea1-8085-47a2-8e08-2d6324efabe1

**Comment by Jaimin25** [comment]
If this is still a problem, I have a solution and work on it @bigint 

https://github.com/heyxyz/hey/assets/65119631/fde73f91-0181-4a18-b56b-48dbe8d3aca8

**Comment by Jaimin25** [comment]
@bigint should I submit a pr?

**Comment by bigint** [comment]
Feel free to do it @Jaimin25 🙇🏼

**Comment by bigint** [comment]
Fixed
