### ISSUE TITLE
Blocking a User displays wrong notification

### ISSUE THREAD

**Issue by DanIsNearby** [heyxyz/hey#3950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Unblocked Sucessfully" notification

### Expected Behavior

"Blocked Sucessfully" notification

### Steps To Reproduce

Block somone on lens for example https://hey.xyz/u/gotenks

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Fixed
