### ISSUE TITLE
Fix error on switch profile to auto prompt wallet if logged out or incorrect

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#3970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

Profile menu > Switch profile

### Expected Behavior

Should show profile list for switching

### Current Behavior

Error message:

> Failed to load profiles
> Response not successful: Received status code 400

![Screenshot_2023-11-07_13-38-31](https://github.com/heyxyz/hey/assets/667227/e38283bb-de50-439c-be44-ff377b1e953b)

https://github.com/heyxyz/hey/assets/69431456/a199da37-e401-47a2-a3d5-f6dcadd46ff1

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is because wallet got disconnected 🙈 we need to fix this!

**Comment by bigint** [comment]
we need to say user to reconnect the wallet!

**Comment by adelinaenache** [comment]
/attempt #3970
May I work on this?

**Comment by bigint** [comment]
@adelinaenache sure do you have experience with web3 wallets?

**Comment by bigint** [comment]
Updated the description to reproduce this error

**Comment by adelinaenache** [comment]
@bigint no, not much as a developer, but I am willing to learn!

**Comment by nermalcat69** [comment]
I'm not really sure what u really need, but trying my chance

**Comment by guptadeepak8** [comment]
Hey @bigint, just to clarify, when a user disconnects, do we want to prompt them to switch accounts and display a toast error indicating the disconnection? If I understand correctly, we need to inform the user to reconnect the wallet. Is this correct?

**Comment by guptadeepak8** [comment]
Or to prompt to connect to wallet

**Comment by guptadeepak8** [comment]
Hello @bigint, I wanted to ask when the user is logged out, they are prompted to log in so users can not switch account. Do you want to display a login prompt when the user is somehow disconnected from the wallet?

**Comment by chintanpuggalok** [comment]
trying it out
/attempt #3970
