### ISSUE TITLE
when i mirror stani post

### ISSUE THREAD

**Issue by makhdoom13** [heyxyz/hey#3983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i mirror stani post. i got this message (Momoka is currently in beta - during this time certain actions are not available to all profiles) and can,t post or mirror free of cost.always pay 0.01 upto 0.04$

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

i m sponsor of hey.xyz last 5 months.kindly solve my issue.

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
