### ISSUE TITLE
Full size images loaded for pfp thumbnails in feed

### ISSUE THREAD

**Issue by foolo** [heyxyz/hey#4013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For profile thumbnails in the feed, a large version of the image (up to around 1MB) is used, so scrolling though the feed will consume a lot of network traffic.

https://github.com/heyxyz/hey/assets/667227/5386f557-8efe-405f-9d97-d33e2136ce83

### Expected Behavior

Should load down-scaled versions of the images

### Steps To Reproduce

Scroll though the feed, open some of the profile picture thumbnail images in a new tab

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Again this is issue with api 🙈 they need to snapshot all images to imagekit URLs, I reported to the team, should be fixed ASAP!

**Comment by foolo** [comment]
> Again this is issue with api 🙈 they need to snapshot all images to imagekit URLs, I reported to the team, should be fixed ASAP!

@bigint Ahh, okay. I thought that the previous problem (i.e. the same problem :) ) was supposed to be resolved in just a few days or so, so I figured something was wrong here.

**Comment by foolo** [comment]
duplicate of https://github.com/heyxyz/hey/issues/3634
