### ISSUE TITLE
Something went wrong?

### ISSUE THREAD

**Issue by geoffzanelli** [heyxyz/hey#4025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm currently experiencing an issue where I can't post. After signing in the last step, a 'something wrong' dialog box appears, preventing me from posting on Hey. Additionally, I can't link my account on Phaver.
![Screenshot_2023-11-16-12-08-06-339-edit_io metamask](https://github.com/heyxyz/hey/assets/66299707/45592d16-e4d2-4b7d-bc90-33f898f987af)

### Expected Behavior

hope to get a resolution.

### Steps To Reproduce

idk.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Fixed
