### ISSUE TITLE
Improve web-vitals to all green / score above 80

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4029]
This is the report RN https://pagespeed.web.dev/analysis/https-hey-xyz/p20kdhkw4h?form_factor=mobile

**Comment by rishi-raj-jain** [comment]
@bigint for homepage that is?

**Comment by rishi-raj-jain** [comment]
@bigint for homepage that is?

**Comment by bigint** [comment]
@rishi-raj-jain I guess fixing it will fix almost on all pages 🤞🏼 

Lets do this bounty only for homepage now! but both on web and mobile!!

**Comment by rishi-raj-jain** [comment]
@bigint 

Alright, let's do it.

Is the feed refreshed automatically or does one need to reload the page on the homepage?

**Comment by rishi-raj-jain** [comment]
The critical thing here is LCP. For the homepage, both in mobile and web, LCP is the cause of the issue. I've a way to improve that based on the answer above.

**Comment by rishi-raj-jain** [comment]
I just looked into the codebase again, not as quick as I thought.

**Comment by rishi-raj-jain** [comment]
@neo773 wanna try this one?

**Comment by neo773** [comment]
@rishi-raj-jain 
I'm kind of burned out atm XD
Thanks for asking tho

**Comment by rishi-raj-jain** [comment]
haha, but you are crushing it.

**Comment by neo773** [comment]
> haha, but you are crushing it.

We both seem be to :D

**Comment by neo773** [comment]
@rishi-raj-jain 
Could you try removing [Loader.tsx] ?(https://github.com/heyxyz/hey/blob/1f5f5fc23227270869ec113450cd6087ff29d9db/apps/web/src/components/Shared/Loader.tsx)

I read an article some time ago that they slow down the page and impact LCP.

**Comment by rishi-raj-jain** [comment]
@neo773 

Nah, removing the loader would be one of the steps I believe. The page that google indexes see `Explore/Feed.tsx` and we need to optimise that. I wish if there's a way to make a single item call, right now the lowest limit to fetch the number of items on the feed are 10 (from the enum)

But that feed is shown after doing about 3-5 requests. The whole thing can be changed to show the loading feed first, logic later.

**Comment by rishi-raj-jain** [comment]
Being more focused would be to do a getStaticProp with that feed. Trying that.

**Comment by rishi-raj-jain** [comment]
Seems beyond my scope at the moment.

**Comment by bigint** [comment]
Would suggest to stick with CSR!

**Comment by bigint** [comment]
We have already improved tons now except performance!

https://pagespeed.web.dev/analysis/https-hey-xyz/nza2dllh3h?form_factor=mobile

**Comment by surendrasomai** [comment]
Thank you for the update, I am working on it , what about your status @rishi-raj-jain

**Comment by rishi-raj-jain** [comment]
Feel free to take this, definitely beyond my capabilities for now.

**Comment by bigint** [comment]
Closing this bounty as no one picked it!
