### ISSUE TITLE
I can no longer insert emojis directly when writing post/comment

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After typing ":" followed by a emoji keyword nothing happens right now when writing a post/comment.

### Expected Behavior

Before, after typing ":" and writing emoji keyword a few emoji options would appear to chose from.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Fixed
