### ISSUE TITLE
mostly user unable to connect lens profile

### ISSUE THREAD

**Issue by makhdoom13** [heyxyz/hey#4044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![WhatsApp Image 2023-11-20 at 21 09 34](https://github.com/heyxyz/hey/assets/118660076/53d264d7-3671-4f70-bdf6-750612a12f4d)

### Steps To Reproduce

Something went wrong!

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![WhatsApp Image 2023-11-20 at 21 09 34](https://github.com/heyxyz/hey/assets/118660076/c22fb457-48a4-4b99-9e76-1881a07d1c88)

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
