### ISSUE TITLE
i can post others twitters

### ISSUE THREAD

**Issue by UncleWu1** [heyxyz/hey#4048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

   when i clik the post ,i can't do nothing
![image](https://github.com/heyxyz/hey/assets/93319321/42da5249-a9a1-416c-ade5-5cbf49bfb6ad)

### Expected Behavior

i should post my view success

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
