### ISSUE TITLE
Testnet.hey.xyz is not working 

### ISSUE THREAD

**Issue by Haris007-M** [heyxyz/hey#4067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testnet.hey.xyz is not working 

### Expected Behavior

Testnet.hey.xyz is not working 

### Steps To Reproduce

Testnet.hey.xyz is not working 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Testnet.hey.xyz is not working

**Comment by bigint** [comment]
Fixed
