### ISSUE TITLE
Acount ZN @02028

### ISSUE THREAD

**Issue by ZMSVC** [heyxyz/hey#4082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following bugs have not been remedied

Failed to load timeline
Response not successful: Received status code 401

Signless transactions
You can enable Lens manager to interact with Hey without signing any of your transactions.

### Expected Behavior

The following bugs have not been remedied

Failed to load timeline
Response not successful: Received status code 401

Signless transactions
You can enable Lens manager to interact with Hey without signing any of your transactions.

### Steps To Reproduce

The following bugs have not been remedied

Failed to load timeline
Response not successful: Received status code 401

Signless transactions
You can enable Lens manager to interact with Hey without signing any of your transactions.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

The following bugs have not been remedied

Failed to load timeline
Response not successful: Received status code 401

Signless transactions
You can enable Lens manager to interact with Hey without signing any of your transactions.

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
