### ISSUE TITLE
Logo Alignment Issue on Mobile and Tablet Views

### ISSUE THREAD

**Issue by parv8055** [heyxyz/hey#4086]
### Summary

When accessing the website on **mobile** and **tablet** devices, the logo does not appear centered as expected. This misalignment affect may impact user experience.Attaching screenshots illustrating the issue on both **mobile** and **tablet** devices.
 
[
![Untitled design](https://github.com/heyxyz/hey/assets/104005053/edfea0a0-70cd-43c9-9a84-15086b4c9ba4)
](url)

**Comment by bigint** [comment]
<img width="527" alt="Screenshot 2023-12-01 at 7 07 33 PM" src="https://github.com/heyxyz/hey/assets/69431456/13c450a6-0b60-46ce-9ad0-3ffdd45bf7a3">

I can't repro 🙇🏼

**Comment by parv8055** [comment]
i can fix this issue

**Comment by parv8055** [comment]
i think i pulled the old branch
