### ISSUE TITLE
OG Image for social previews

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4089]
https://hey.height.app/engineering/T-827

**Comment by rishi-raj-jain** [comment]
Thanks for assigning!

**Comment by rishi-raj-jain** [comment]
I'm working on it.

**Comment by rishi-raj-jain** [comment]
Haha nah I'm just focusing on two things atm. This is what I've been conversing about @bigint with already

**Comment by Rutik7066** [comment]
no problem i will do it now no matter what and for free

**Comment by rishi-raj-jain** [comment]
okay

**Comment by Rutik7066** [comment]
haha ha

**Comment by Rutik7066** [comment]
Hey @rishi-raj-jain continue now. i got other contract now. bythe way og is implemented in meta tag already. good luck !

**Comment by rishi-raj-jain** [comment]
Thanks for the wish!

**Comment by Rutik7066** [comment]
> https://hey.height.app/engineering/T-827

Hi @bigint could you please provide me more details about the issue as i can see in web their is already opengraph is implemented in meta elements is there anything to change or implement. 
I am willing to solve this issue.

**Comment by sc0rp10n-py** [comment]
@bigint what is left in this?
