### ISSUE TITLE
Can not unfollow

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to unfollow a certain profile on Lens, but I got the following message:

> cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x25418Bcf53dAe1167cD5d0cad34Eec31C0C37E41","to":"0xDb46d1Dc155634FbC732f92E853b10B288AD5a1d","data":"0x815ed04a000000000000000000000000000000000000000000000000000000000001a6b300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000001c820","accessList":null},"error":{"code":3,"data":"0x8b67bbcc"}}, tx={"data":"0x815ed04a000000000000000000000000000000000000000000000000000000000001a6b300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000001c820","to":{},"from":"0x25418bcf53dae1167cd5d0cad34eec31c0c37e41","gasLimit":{},"speed":"fastest"}, code=UNPREDICTABLE_GAS_LIMIT, version=defender-relay-client)

I tried this using a profile manager wallet, not the wallet where is the actual profile is stored. Might that be the reason of unsuccessful unfollow operation?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by aurosevic** [comment]
Could you inform the backend team of the issue?
