### ISSUE TITLE
Replies are not hidden on deleted parent post

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4151]
https://hey.xyz/posts/0x24-0x09b8-DA-5ae29f58

**Comment by crediblebilal** [comment]
Hey @bigint , if this is still open, I wanted to work on this issue. Assign it to me.

**Comment by bigint** [comment]
Assigned @crediblebilal

**Comment by crediblebilal** [comment]
should we display any message in place of the replies for deleted posts? or we just need to hide all the replies without any message?

**Comment by bigint** [comment]
<img width="848" alt="Screenshot 2023-12-12 at 10 44 13 PM" src="https://github.com/heyxyz/hey/assets/69431456/79516a4b-2299-48d8-a504-04acb93f7c6b">

just use this comp
