### ISSUE TITLE
Add proper cors validation on api and allow specific endpoints

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4155]

**Comment by Ameer-officials** [comment]
which endpoints to be allowed?

**Comment by bigint** [comment]
```
https://hey.xyz
https://*.hey.xyz
https://*-heyxyz.vercel.app
http://localhost:4783
```

we need to make sure wild card is supported

**Comment by tahamukhtar20** [comment]
is this issue assigned or can I work on this?

**Comment by bigint** [comment]
We no longer need this, cuz the solution on app layer will not be a good solution, we implemented this on firewall level to prevent any traffic before hitting the box!
