### ISSUE TITLE
Migrate composer to TipTap editor

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4169]
https://tiptap.dev/

We need to make sure the output should be in markdown also it need to support all existing plugins mainly the mentions

**Comment by rajdip-b** [comment]
@bigint can you please assign this to me?

**Comment by rajdip-b** [comment]
Thanks!!!

**Comment by bigint** [comment]
Done, will be unassigned if the Draft PR is not raised for 2 days 🙇🏼

**Comment by rajdip-b** [comment]
> Done, will be unassigned if the Draft PR is not raised for 2 days 🙇🏼

on it!

**Comment by neo773** [comment]
Hi,

Would like to be next in line if PR is not raised.

**Comment by rajdip-b** [comment]
@bigint do i need to change only the editor (place where we write stuff), or the entire composer component? to be more precise, the code already uses the lexical package. so do i use the existing lexical code along with new tiptap editor code, or do i replace everything with tiptap?

**Comment by bigint** [comment]
@rajdip-b the goal is to RIP entire lexical from the service, because of its size 🙇🏼 

Do you think migrating to tiptap will reduce the size? if so we can move forward

**Comment by rajdip-b** [comment]
> @rajdip-b the goal is to RIP entire lexical from the service, because of its size 🙇🏼
> 
> Do you think migrating to tiptap will reduce the size? if so we can move forward

I don't have much experience with TipTap, but what I can feel is, it is headless, and so you have to manually create many components (the toolbar for example). So it's up to you to decide! 

Also, if I were to RIP the entire lexical system, it might take up some time since it's tremendous big. Coding the thing is something, testing is another level of pain!

**Comment by bigint** [comment]
Yes actually this issue is all about migrating everything from lexical to tip tap 🙈

**Comment by bigint** [comment]
But only if size is less comparatively

**Comment by rajdip-b** [comment]
@bigint I might not be the best person to take this decision perhaps :(

**Comment by neo773** [comment]
@rajdip-b @bigint 

I did some analysis on the production bundle we're shipping roughly `210kb` of lexical code which seems to about right when calculating each module size

```
@lexical/code 82.6kb
@lexical/markdown@ 122.5kb
@lexical/hashtag 16.7kb
@lexical/link 20.3kb
@lexical/clipboardd 23.6kb
Total 265.7kb
```
source: bundlephobia

<img width="737" alt="SCR-20231211-sddd" src="https://github.com/heyxyz/hey/assets/62795688/6feb1207-786f-4510-b303-958935cf250b">

Tiptap's around `210.2kb` considering average 20% reduction by tree shaking this would minimum `168kb` actual number could be even lower based on what we're importing.

**Comment by bigint** [comment]
@neo773 I think it will add extra when we add tiptap mention extension 🤔

**Comment by bigint** [comment]
Also dropping the reference from lu.ma https://lu.ma/style-guide/editor

**Comment by neo773** [comment]
@bigint 
Mention extension is surprisingly only [2.2KB](https://bundlephobia.com/package/@tiptap/extension-mention@2.1.13) minified

**Comment by rajdip-b** [comment]
@bigint so should i proceed with this?

**Comment by bigint** [comment]
@rajdip-b again the goal of the PR is to

- reduce the bundle size (high priority)
- improve dx
- should satisfy all conditions

I don't find time to analyze, this bounty covers everything!

**Comment by rajdip-b** [comment]
@bigint then I feel @neo773 might be better suited for this since he has done his research!

**Comment by Rutik7066** [comment]
hey @bigint could you please navigate me

**Comment by bigint** [comment]
We gonna stick with Lexical, we improved a lot
