### ISSUE TITLE
Fix liking a publication re-renders entire feed

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4188]
https://github.com/heyxyz/hey/assets/69431456/260cc93e-280d-40cb-953f-c9d7f99dcf6c

**Comment by RutamBhagat** [comment]
![Screenshot from 2023-12-12 13-50-33](https://github.com/heyxyz/hey/assets/72187009/1231d7f0-2b14-4772-820d-9441d051a8c4)
@bigint  Is there a way to test the liking without a lens profile?

**Comment by bigint** [comment]
@RutamBhagat Try with testnet, change your env to testnet then create an account (click login -> create new account)

**Comment by bigint** [comment]
https://github.com/heyxyz/hey/blob/main/docs/development.md#create-a-lens-account-for-development

**Comment by rajdip-b** [comment]
@bigint I tried this on my device but wasn't able to reproduce the bug.

**Comment by bigint** [comment]
@rajdip-b you not seeing rerenders? can you make a short video and share 🙇🏼 ?

**Comment by RutamBhagat** [comment]
the rerenders are visible for me

**Comment by rajdip-b** [comment]
That's odd. I'm using firefox. Perhaps you can tell me where I should focus on? I was looking at the DOM tree from the inspect tab.

**Comment by bigint** [comment]
You should use react chrome extension and enable rerender paints!

**Comment by bigint** [comment]
<img width="546" alt="Screenshot 2023-12-12 at 3 23 27 PM" src="https://github.com/heyxyz/hey/assets/69431456/5dbf13f0-b1dd-49a9-92b6-e313f453531e">

**Comment by rajdip-b** [comment]
Ahh, okay looks like I need to switch to chrome for dev 🥲.

**Comment by RutamBhagat** [comment]
@rajdip-b you can work on this, I am cancelling my attempt

**Comment by rajdip-b** [comment]
@RutamBhagat sure! can you give me some insights about anything that you might have came across that is making this issue?

**Comment by rajdip-b** [comment]
@bigint is this bug localized to the "Home" section alone? or is it happening in explore aswell?

**Comment by bigint** [comment]
it happens on all feed @rajdip-b 🙇🏼

**Comment by rajdip-b** [comment]
@bigint can you assign me this one please?

**Comment by rajdip-b** [comment]
@bigint hey, i seem to have fixed the issue. 
![image](https://github.com/heyxyz/hey/assets/83924254/724beceb-1cab-4447-89e6-eadb623631f2)
 it involves removing the updateCache function. but i am unsure about the side effects of this. rest assured, the app looks and performs like it is supposed to. care to give it a look?

**Comment by bigint** [comment]
@rajdip-b the cache is intended to update values across components

Here is the example, both are different comp but we update it 😉 

https://github.com/heyxyz/hey/assets/69431456/a6e71529-6ec9-402a-b8df-cd0168193281

**Comment by rajdip-b** [comment]
checked this component aswell, the entire component is re-rendering. is this expected?

> @rajdip-b the cache is intended to update values across components
> 
> Here is the example, both are different comp but we update it 😉
> Screen.Recording.2023-12-12.at.7.02.57.PM.mov

**Comment by bigint** [comment]
It is expected to rerender only the count but not the complete publication 🙇🏼

**Comment by rajdip-b** [comment]
got it

**Comment by rajdip-b** [comment]
Hey @bigint, I don't know if I am seeing this correct, but I really feel that there is no re-rendering going on. I added a console log to the publication component that will execute every single time the component was rendered. And as I expected, only those components were re-rendered where I was liking/unliking.
![image](https://github.com/heyxyz/hey/assets/83924254/e183c81a-edd2-420b-becc-f55011287376)

Check the logs section, might give you the idea about what I am saying.
[Screencast from 12-12-23 07:32:15 PM IST.webm](https://github.com/heyxyz/hey/assets/83924254/b8aadd1a-ac7a-4b1e-a23d-eb89ed6ab66a)

**Comment by bigint** [comment]
Interesing, lemme try it

**Comment by GauravBurande** [comment]
It looks like no one is working on this issue. can I work on this?
