### ISSUE TITLE
Disable scroll on react calendar on profile stats page

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4191]
![Image](https://github.com/heyxyz/hey/assets/69431456/aa4f807d-35aa-4f6f-9dff-f64bcb6c37de)

**Comment by Min2who** [comment]
can i get assigned?

**Comment by bigint** [comment]
FCFS 😉

**Comment by Ameer-officials** [comment]
![Screenshot 2023-12-12 153423](https://github.com/heyxyz/hey/assets/123060761/837c7bed-98da-41d1-899e-b98d3b41843f)

browser wallet is not supported , what to do?

**Comment by bigint** [comment]
@Ameer-officials do you have wallet installed?

**Comment by bigint** [comment]
If not install it from here https://metamask.io/download/

**Comment by rajdip-b** [comment]
hey @bigint, disabling the scroll wont allow the users to view the activity. do you want to disable it or hide the scroll bar?

**Comment by rajdip-b** [comment]
Cancelling my attempt since @neo773 has submitted a working pr
