### ISSUE TITLE
Integrate realtime DMs with Push Protocol

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4240]
- Able to chat between two lens profiles (not wallets)
- Should be realtime
- Ability to upload images and videos
- Ability to react on messages
- Ability to reply to messages
- Make sure to follow Hey coding standards

Bounties will be paid on every big milestone as Algora tip

https://push.org/docs/chat/build/

Can jump on a call for a discussion

PS: no one will be assigned, I will review all PRs, lets see who gonna grab em all 😉 
```[tasklist]
### Tasks
- [ ] Add optimisting send in DMs aka fake sending message, same like whatsapp does!
```

**Comment by b4s36t4** [comment]
@bigint I'm taking this up.

**Comment by b4s36t4** [comment]
Was there any design for this @bigint ?

**Comment by bigint** [comment]
@b4s36t4 You can follow twitter like approach now! aka DMs are more general to all socials!

**Comment by b4s36t4** [comment]
Ok, but you said amount is paid on feature/milestone based. But without assigning how do you manage milestones?

**Comment by bigint** [comment]
Y'all we switched from xmtp to push protocol

XMTP is very limited and slow for huge wallets!

https://github.com/heyxyz/hey/assets/69431456/211639fd-37cb-40e0-8da8-da1ab73930f6


cc @neo773 @b4s36t4

**Comment by b4s36t4** [comment]
Seems push dev network is not working :(

**Comment by bigint** [comment]
@b4s36t4 what is not working, what kind of error you are seeing? can you DM me on discord/telegram 🙇🏼 ?

**Comment by bigint** [comment]
Here are socials https://pastes.io/b6jcjhxjlz

**Comment by b4s36t4** [comment]
@bigint  In favour of moving from xmtp to push I created new PR (#4251)

**Comment by hashtagobi1** [comment]
Hi @bigint,

I hope you are well.

I'd love to give this a go. I've created a brief demo over at:  **[https://chat-firebase-dun.vercel.app/](https://chat-firebase-dun.vercel.app/)**

- Open and Sign in with 2 browsers 
- Test out chat functionality

Stack Used:
- Typescript
- Firebase
- ClerkJS
- Next.JS
- Framer Motion
- Tailwind

/claim #4240

**Comment by bigint** [comment]
@hashtagobi1 we need to use push sdk here 🙇🏼

**Comment by hashtagobi1** [comment]
@bigint Yes of course. I've read through the docs. It seems this is still unsolved? I will start my attempt now.

**Comment by oliverqx** [comment]
Is this still open?

**Comment by hangyakuzero** [comment]
Hey since this issue has not been resolved yet, all you have to do is integrate  push protocol using the sdk right? no major changes in the frontend or UI/UX?, lemme fork the repo and work on it, do you want to include group messages as well?

**Comment by Ahmadkhan02** [comment]
@bigint  is this still open?
