### ISSUE TITLE
Add quotes page showing all quoted publications

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4244]

**Comment by Vayras** [comment]
Hey @bigint  I wish to contribute towards this can you please provide me with issue description and assign me to this attempt #4244

**Comment by bigint** [comment]
@Vayras when you open some publication ex: https://hey.xyz/posts/0x01-0x02bb-DA-8ecfe472 on clicking quotes it displays only who quoted, instead we need to make a separate page that shows all quotes something like twitter does

luckily the publication object is on the user list itself, you just need to copy paste some feed component and change queries and object!

https://github.com/heyxyz/hey/assets/69431456/e47cdd2a-edff-4645-a5be-0a308a8d6dcb
