### ISSUE TITLE
UI: Design select menu

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4246]
https://tailwindui.com/components/application-ui/forms/select-menus

Props:

- options[]
  - title: ReactNode 
  - description: ReactNode
  - key: string
  - value: string
-  `...rest` of HTML select

**Comment by bigint** [comment]
Updated description

**Comment by Akashpaila** [comment]
Is it open now ?

**Comment by RutamBhagat** [comment]
> Is it open now ?

@Akashpaila waiting for approval for #4259

**Comment by bigint** [comment]
Done
