### ISSUE TITLE
Alphanumeric should handle both Uppercase and Lowercase

### ISSUE THREAD

**Issue by aadarsh-nagrath** [heyxyz/hey#4288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So, While logging in, the option of creating a testnet Account appears.
![image](https://github.com/heyxyz/hey/assets/92307537/5283f16a-146e-41c6-a27f-f0588a3ee15a)
If You enter A uppercase Handle name, it will suggest entering an alphanumeric name, But Alphanumeric is -> "simply refers to the type of Latin and Arabic characters representing the numbers 0 - 9, the letters A - Z (both uppercase and lowercase)".

Entering an uppercase letter won't work like -> Hello990, but if you enter it in lowercase, hello990, it works.

It should also handle Uppercase alphanumeric, or it should specify in lowercase 
![Screenshot 2023-12-19 233713](https://github.com/heyxyz/hey/assets/92307537/23aa0cd9-2153-490f-8f5d-e5f839cbd57e)

### Expected Behavior

Should handle both lowercase and Uppercase Alphanumeric or should be specified to enter in lowercase

### Steps To Reproduce

Login -> Create testnet Account -> Enter World123 the  try with world123

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

I tried on Opera.

**Comment by bigint** [comment]
Fixed
