### ISSUE TITLE
Migrate away from all headless ui usage to use radix primitives

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4327]

**Comment by neo773** [comment]
can i get assigned

**Comment by bigint** [comment]
If a draft PR is not raised for 24 hours, you will get un-assigned 🙇🏼

**Comment by sdthakral33** [comment]
I would like to work on this assignment. Please assign it to me.

**Comment by parv8055** [comment]
Can i try

**Comment by parv8055** [comment]
can i try

**Comment by mrkirthi-24** [comment]
/attempt #4327
I am in the waitlist

**Comment by bigint** [comment]
Fell free to pick @mrkirthi-24

**Comment by sdthakral33** [comment]
@bigint I am almost done with this assignment. Will be raising a PR in sometime.
