### ISSUE TITLE
Serbian flag icon is broken

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on the post views, I notice that the list of countries with flags is displayed. However, Serbian flag icon appears broken. Here's an example post: https://hey.xyz/posts/0x01a6b3-0x01ca-DA-edd1f914

By the way, I love this feature!

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
We removed this feature
