### ISSUE TITLE
Not all Smileys/Icons work

### ISSUE THREAD

**Issue by airx3** [heyxyz/hey#4509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I want to do a posts i have a lot of smileys/icons that does not work:
![smiley](https://github.com/heyxyz/hey/assets/66184142/61963db8-d607-409b-b740-06779d6033ad)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Its a system level issue
