### ISSUE TITLE
Uploading issue using hey 

### ISSUE THREAD

**Issue by sdkdeepak146** [heyxyz/hey#4510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wallet connect isn't working well through mobile application, it's happening continuously after lens v2 migration happened 
![Screenshot_20240108_171751](https://github.com/heyxyz/hey/assets/141130817/5a31b748-444a-4218-ae2e-6d2c22134861)

### Expected Behavior

Need to raise issue with wallet connect so it can help application work better with its competitors 

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

![Screenshot_20240108_171751](https://github.com/heyxyz/hey/assets/141130817/c3940a0d-180b-4678-be70-6c8afad462b7)

**Comment by bigint** [comment]
Should be fixed!
