### ISSUE TITLE
When any picture is opened it blends with the rest of the UI

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open any picture: from post/profile pic, ... it blends into the rest of the UI.

![Screenshot_20240113_005503](https://github.com/heyxyz/hey/assets/19304661/2c12fd82-ef0d-42b8-bc33-a195f6422213)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by andrew112196** [comment]
Great find

**Comment by aurosevic** [comment]
Update:
Now the picture opens, but the preview is too small. Love the rounded corners btw!

![Screenshot_20240126_225401-1](https://github.com/heyxyz/hey/assets/19304661/26a5e900-f65a-44b9-a263-fb3634149a5a)

**Comment by trisid12** [comment]
is this issue still open?

**Comment by aurosevic** [comment]
Hi @trisid12, the comment containing update of the issue is still relevant.

https://github.com/heyxyz/hey/issues/4525#issuecomment-1912747759
