### ISSUE TITLE
Can not post on Hey

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have tried to post and comment on Hey in the past 30 minutes, but none of my posts and comment were submitted.
Here's a video where I'm trying to post. There are two additional problems that are visible on video:
1. Collect setting would not load
2. At the upper left corner of the Mint card made from the video link i've included inside the post appears my name Andrija, but the video was uploaded using Babylon Analytics account.
3. (bonus) Image upload was unexpectedly slow. I've checked the status and speed of the network I'm using, that should not be the problem.

https://github.com/heyxyz/hey/assets/19304661/34a6ee6b-21eb-4df2-aa64-045404109003

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by aurosevic** [comment]
This is the post I've been able to submit: https://hey.xyz/posts/0x01a9fd-0x010b
And it looks different in comparison to the post preview. What is missing is the video that on preview was shown as a collectable frame.

**Comment by bigint** [comment]
It might be due to some network issue with Irys or Lens API
