### ISSUE TITLE
Local development - no way to create a testnet account

### ISSUE THREAD

**Issue by adevinwild** [heyxyz/hey#4596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While I was trying to set up my local environment so that I could contribute to the project, I realized that the development guide may no longer be up to date.

At present, it's impossible to create a testnet account, and there's no button in the codebase that would allow such an action (`Create testnet account`)

### Expected Behavior

Based on the [local development guide](https://github.com/heyxyz/hey/blob/main/docs/development.md#create-a-lens-account-for-development), it is indicated at step: 
```
4. Click the "Create a testnet account" button.
```

> [!NOTE]  
> After a little investigation on the repo, it seems that the testnet registration button has disappeared on this commit:
> https://github.com/heyxyz/hey/commit/1fc41c8cfed1b222e56277a4d5ce2d3121227f81

### Steps To Reproduce

Screenshots of the current behavior : 
![image](https://github.com/heyxyz/hey/assets/68734155/6b9fe3de-cebc-4e76-8baf-6025371f5600)
> After a click on the `Login` button

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Documentation could potentially be updated to indicate the new way of creating a testnet account to start contributing to the project.

**Comment by bigint** [comment]
We are going permissionless soon 🙇🏼 stay tuned 🙏🏼
