### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#46]
null

<sub>[ENG-58](https://linear.app/heyxyz/issue/ENG-58/add-about-page)</sub>

**Comment by vinliao** [comment]
Rough sketch, rough first draft.

![Desktop - 1(2)](https://user-images.githubusercontent.com/34117807/187017458-49265fa6-c393-4a35-962c-4904ebc0e3a8.png)

**Comment by jayantdahiya** [comment]
Hi @bigint , I have designed a layout as well. Let me know what you think of this one 😊
![Lenster_about_UI](https://user-images.githubusercontent.com/31251655/187658323-5bd05679-460d-432c-82b8-06e21c7be26c.png)

**Comment by bigint** [comment]
We are expecting design something like this 🙏🏼 

https://vk.com/about

**Comment by vinliao** [comment]
![Desktop - 2(1)](https://user-images.githubusercontent.com/34117807/187855235-0efd9278-4946-4646-860b-604afe36d665.png)

Note: Just to clarify, is the design enough, or should there be a code PR that implements the design?

**Comment by bigint** [comment]
@vinliao we should have code too 🙇🏼

**Comment by bigint** [comment]
@vinliao useful links look bit odd we can remove it

**Comment by shanpriyan** [comment]
I can take this up, if no one is working on this issue

**Comment by 0xchetan** [comment]
@bigint do we have content for this page?

**Comment by foolo** [comment]
@vinliao Seems from @bigint's comment https://github.com/lensterxyz/lenster/issues/46#issuecomment-1234304086 that your design is fine if we just remove Useful links. Do you plan to implement this PR? Otherwise I'll grab it.

**Comment by vinliao** [comment]
Please do, I'm not actively working on this issue right now.

**Comment by jayantdahiya** [comment]
Hi @bigint, I've coded this layout for the About Page. Let me know what you think about it 🤗


https://user-images.githubusercontent.com/31251655/224541280-b9ce911e-b338-4c10-884c-bfba066d7ebc.mov
