### ISSUE TITLE
Navigation bar is not fixed

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Navigation bar is not persistent at the bottom of the app. Sometimes, on mobile it floats with the scroll. 

https://github.com/heyxyz/hey/assets/19304661/a3599936-237d-4e03-8722-52ad8bb42263

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Safari

**Comment by richardgreg** [comment]
Steps To Reproduce?

**Comment by aurosevic** [comment]
Unfortunately, I do not have a guide to reproduce the behavior. It just happens from time to time, and I can not tell the reason why and when.

**Comment by bigint** [comment]
Can't repro as well
