### ISSUE TITLE
Geographical segmentation of views counts on posts leaks users country

### ISSUE THREAD

**Issue by random-potential** [heyxyz/hey#4612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As post views counter segments viewers by country, it is extremely easy to find country of a specific user: 

1. Use an account with little to no followers to post a reply to their reply (the deeper in the comment thread the better). 
2. Wait for the first view to come and check viewers county. It will most often be the targeted account.
3. You can repeat more times to see what country comes up most often to make a more precise guess.

### Expected Behavior

Solution:

1. Do not segment viewers by country on comments, only on posts.

I know, these stats look nice, I like checking them out too. However, privacy is more important, isn't it?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
I can add threshold, like once you get 50 views we can show the list of countries. wdyt?
