### ISSUE TITLE
Video playback failed

### ISSUE THREAD

**Issue by aurosevic** [heyxyz/hey#4657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have uploaded a video using Orb, and on Hey there are no visuals, just an audio. I am getting "Playback failed" error on top of the video player.

Here's the link to the video: https://hey.xyz/posts/0x01a6b3-0x01f4-DA-6a8561ad

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Brave, Safari

**Comment by bigint** [comment]
It's happening on Tape as well https://tape.xyz/watch/0x01a6b3-0x01f4-DA-6a8561ad

It should be issue with the Orb uploading their videos 🙇🏼

**Comment by aurosevic** [comment]
I have written to them as well ✌🏻
