### ISSUE TITLE
Post link preview displayed incorrectly 

### ISSUE THREAD

**Issue by random-potential** [heyxyz/hey#4691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a post, link preview of an internal Hey post with collects enabled is displayed as a preview of an external link with an option to mint. On top of that, the preview thumbnail itself is broken / not available.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![image](https://github.com/heyxyz/hey/assets/140802576/cf8c36cf-32de-42cc-b84d-b446c1b634e7)

https://hey.xyz/posts/0xe30c-0x0297

**Comment by phg5uzfc** [comment]
same here
