### ISSUE TITLE
Unable to delete post you have mirrored

### ISSUE THREAD

**Issue by rex4539** [heyxyz/hey#4729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mirrored post cannot be deleted.

### Expected Behavior

Mirrored post is deleted.

### Steps To Reproduce

1. Post something.
2. Mirror it.
3. Delete the mirrored post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Safari

**Comment by 0xkakas** [comment]
Agree. One should be able to unpost or delete the mirrored post.

**Comment by defispartan** [comment]
Agree this can be frustrating, especially when accidentally clicking "Mirror Again"
