### ISSUE TITLE
Migrate the composer to Prosekit

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4811]
https://prosekit.dev/

Have done base work here: https://github.com/heyxyz/hey/pull/4810

https://yoginth.notion.site/4e4a0a7547134c03ba8096fd26e76c05

**Comment by neo773** [comment]
Just writing from my own experience the OP has a history of changing his mind at last moment and won't even give you a reply for months.

I worked on a big bounty for over a month along side a competing team, the OP kept ghosting us for weeks when the work was completed and then out of the blue closed the issue with an inadequate reason.

Do what you must with this information.

https://github.com/heyxyz/hey/issues/4240
https://github.com/heyxyz/hey/issues/4169

**Comment by bigint** [comment]
This is assigned to @ocavue

**Comment by adilkadivala** [comment]
hey I want to work on this  /attempt #4811,  but what do you want ?? please explain me..
