### ISSUE TITLE
Support "Pay What You Want" Collects

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#4865]
### Summary

I have created a new type of Collect Module that allows users to "[pay what you want](https://en.wikipedia.org/wiki/Pay_what_you_want)". This affords collectors the ability to use any denomination of any ERC-20 token to collect a publication.

Mainnet: [0x7fbD7496CaE2DAcad7a62350DA8488E31eC026eA](https://polygonscan.com/address/0x7fbD7496CaE2DAcad7a62350DA8488E31eC026eA#code)

Testnet: [0x3d06AA6ca4FC7eE0D5581B85CB52CA7714175e43](https://amoy.polygonscan.com/address/0x3d06AA6ca4FC7eE0D5581B85CB52CA7714175e43#code)

### Notes
- This is a Collect Module, **NOT** a standalone Open Action Module. It is meant to be used with the core `CollectPublicationAction` module. 
- The publication author can optionally specify a desired currency and price floor.

### Implement

The init calldata is almost identical to `MultirecipientFeeCollectModule `:

```
[
  { type: "uint160", name: "amountFloor" },
  { type: "uint96", name: "collectLimit" },
  { type: "address", name: "currency" },
  { type: "uint16", name: "referralFee" },
  { type: "bool", name: "followerOnly" },
  { type: "uint72", name: "endTimestamp" },
  {
    type: "tuple(address,uint16)[5]",
    name: "recipients",
    components: [
      { type: "address", name: "recipient" },
      { type: "uint16", name: "split" },
    ],
  },
]
```

and the process calldata:

```
[
  { type: "address", name: "currency" },
  { type: "uint256", name: "amount" },
]
```

### CollectPublicationAction

This Collect Module is registered with the [CollectPublicationAction](https://polygonscan.com/address/0x0D90C58cBe787CD70B5Effe94Ce58185D72143fB) (the same module used with `SimpleFeeCollectModule` and `MultirecipientFeeCollectModule`). The init calldata is just the Collect Module address and the encoded collect init calldata (above):

```
[
    { type: 'address', name: 'collectModule' },
    { type: 'bytes', name: 'collectModuleInitData' },
]
```

And to process:

```
[
  { type: "address", name: "collectNftRecipient" },
  { type: "bytes", name: "collectData" },
]
```

### Testnet

I have completed a successful `act` call with the PWYW module: https://amoy.polygonscan.com/tx/0xceff77ea12000814d07d3e8bc2b0218ae6ff91e286a08d91872e97b817f4a259

**Comment by punkess** [comment]
what @jamesfinnerty wrote. 
Sounds very fun, imho more fun and interesting ways to collect is sth we should experiment with more.

**Comment by mrsalitre** [comment]
this is genius, agnostic tokens fits perfectly with the permissionless philosophy. I want to see this across the whole lensverse.

**Comment by carstenpoetter** [comment]
this is a great initiative! I applaud this 👏

**Comment by metatxn** [comment]
Totally make sense. How to integrate it?

**Comment by mvanhalen** [comment]
Integrating

**Comment by iPaulPro** [comment]
> Totally make sense. How to integrate it?

It can be added to publications just like any other other Open Action. Only difference with Collect Modules is that they're registered with the existing `CollectPublicationAction` rather than as their own Actions.

Here's a code snippet on how to create the init calldata:

```typescript
import { encodeData } from '@lens-protocol/client';
import { ZeroAddress } from 'ethers';

const EMPTY_RECIPIENT = [ZeroAddress, '0'];

// First, create the PWYW Collect Module init data
const collectInitData = encodeData([
    { type: 'uint160', name: 'amountFloor' },
    { type: 'uint96', name: 'collectLimit' },
    { type: 'address', name: 'currency' },
    { type: 'uint16', name: 'referralFee' },
    { type: 'bool', name: 'followerOnly' },
    { type: 'uint72', name: 'endTimestamp' },
    {
        type: 'tuple(address,uint16)[5]',
        name: 'recipients',
        components: [
            { type: 'address', name: 'recipient' },
            { type: 'uint16', name: 'split' },
        ],
    },
], [
    '0', // amount floor, zero to allow free collects
    '10', // number of mints allowed
    ZeroAddress, // optionally limit to a specific token
    '10', // mirror referral percentage
    false, // minting only for followers
    '0', // optional end date
    [
        ['0x10E1DEB36F41b4Fad35d10d0aB870a4dc52Dbb2c', '5000'],
        EMPTY_RECIPIENT,
        EMPTY_RECIPIENT,
        EMPTY_RECIPIENT,
        EMPTY_RECIPIENT
    ],
]);

// Next, create the CollectPublicationAction init data
const data = encodeData(
    [
        { type: 'address', name: 'collectModule' },
        { type: 'bytes', name: 'collectModuleInitData' },
    ],
    [PWYW_COLLECT_MODULE, collectInitData],
);

// Add as an `unknownOpenAction` to the publication
openActionModules.push({
    unknownOpenAction: {
        address: COLLECT_PUBLICATION_ACTION!,
        data,
    },
});
```

**Comment by Supersigil** [comment]
I've been pestering devs about PWYW for NFTs for years! Makes so much sense, especially for music, given how successful this feature has been on Bandcamp (when given this option, ~50% of fans pay more than the minimum price). I hope this gets implemented across the web3 ecosystem.

**Comment by Prateekrajput1999** [comment]
hey @iPaulPro i very well understood the part of implementation
could u share the act implementation as well...it would be helpful

**Comment by iPaulPro** [comment]
> hey @iPaulPro i very well understood the part of implementation could u share the act implementation as well...it would be helpful i am going to integrate it to SOCLLY soon 🚀

Sure thing! The main thing to note is that the `act is on the `CollectPublicationAction` ([0x0D90C58cBe787CD70B5Effe94Ce58185D72143fB](https://polygonscan.com/address/0x0D90C58cBe787CD70B5Effe94Ce58185D72143fB)) and not the Collect Module, itself, however, the allowance approval must be done with the Collect Module.

Here's an example of process for a 1 BONSAI collect:

```typescript
import { ethers } from "ethers";
import { encodeData } from "@lens-protocol/client";

const processCollectData = encodeData([
  { type: "address", name: "currency" },
  { type: "uint256", name: "amount" },
], [
  "0x3d2bD0e15829AA5C362a4144FdF4A1112fa29B5c",
  ethers.utils.parseUnits("1", 18).toString(),
]);

const processActionData = encodeData(
  [
    { type: "address", name: "collectNftRecipient" },
    { type: "bytes", name: "collectData" },
  ],
  [RECIPIENT, processCollectData],
);
```

Where `RECIPIENT` is the address receiving the Collect NFT.

**Comment by ludmila-omlopes** [comment]
Up vote to have this feature applied to Hey!

While I don't believe all actions should be implemented by all apps on Lens, Hey is usually the first and main contact with the protocol and so suitable for this new monetization feature.

**Comment by hugoreno** [comment]
Awesome feature - would love to see it implemented. We would support with creator tokens on P00LS

**Comment by iPaulPro** [comment]
I created a standalone repository for the PWYW Collect module, with integration instructions:

https://github.com/iPaulPro/pwyw-collect-module

If you want to test it out locally, there's also a branch with it in Scaffold Lens:

https://github.com/iPaulPro/scaffold-lens/tree/feat/pwyw-collect

**Comment by Prateekrajput1999** [comment]
Deployed on [SOCLLY](https://app.soclly.com/) too! ✨
