### ISSUE TITLE
Handles with _ not rendering

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

gm @lens/gf\\_merc\n"

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

gm @lens/gf\\_merc\n"

**Comment by bigint** [comment]
cc @ocavue

**Comment by ocavue** [comment]
I will fix it.
