### ISSUE TITLE
Add hexagon avatars for nft avatars

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#50]
null

<sub>[ENG-59](https://linear.app/heyxyz/issue/ENG-59/add-hexagon-avatars-for-nft-avatars)</sub>

**Comment by andriishupta** [comment]
@bigint I could take it - as I understand - should be similar to Twitter

**Comment by bigint** [comment]
@andriishupta Yup exactly, but only for NFT avatars 🙏🏼
