### ISSUE TITLE
Allow hiding Profile Guardian warnings

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#5017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![hey xyz_](https://github.com/heyxyz/hey/assets/354227/858b5852-5e53-4899-bcd0-146fb4d52201)

Please provide a way to hide this obtrusive banner.

### Expected Behavior

A "close" button on the banner that prevents it from being shown again.

### Steps To Reproduce

Disable profile guardian then visit hey.xyz

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Firefox, Brave, Safari, Edge, Others

**Comment by bigint** [comment]
@iPaulPro Any reasons why we need to hide this?

**Comment by iPaulPro** [comment]
I'd be nice to have a way to optionally hide it, as the user. If I don't want Guardian enabled I'd like to be able to hide that banner so it's not always there.
