### ISSUE TITLE
Links within publications wrapped with braces <>

### ISSUE THREAD

**Issue by defispartan** [heyxyz/hey#5019]
### Summary

Publication created through Hey containing links have braces added to links within the content body. The braces do not appear on Hey but do appear on other other Lens applications.

Example: 

https://hey.xyz/posts/0x2a6b-0x3d

https://node1.irys.xyz/RMQmJnv_1AVTuaJHjoki3ErWBYGRIwal2VmQV7xhKkU

`https://lens-profile-stats-frame.vercel.app/ -> <https://lens-profile-stats-frame.vercel.app/>`

**Comment by iPaulPro** [comment]
Braces around a standalone link is standard Markdown: https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses

**Comment by bigint** [comment]
Yup @iPaulPro is correct, so closing this 🙇🏼
