### ISSUE TITLE
No longer able to see Arweave, Polygon, or Momoka details on posts

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#5028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When viewing a post page we used to have a section in the sidebar that would show the Arweave asset, Polygon transaction, or Momoka proof. This seems to be gone now.

### Expected Behavior

I expect to see those details

### Steps To Reproduce

Go to any post page on Hey

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Yes we removed it while doing a performance boost, we also see there are no much clicks on this area 🙇🏼

**Comment by iPaulPro** [comment]
This is important information and Hey was the only place to easily see it. I hope you'll reconsider. 

Should be able to load this stuff after page load so don't see why it affects performance.
