### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#5031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run the main `dev` script locally everything starts properly except the `api` app which throws:

```
@hey/api:dev: error: Error setting up routes API key is required
```

It's not clear which API key this refers to. Last time I ran I didn't have this issue, so I'm guessing it was something recently added.

Which environmental variables must be declared in the `api` .env?

### Expected Behavior

Able to run the `api` app locally.

### Steps To Reproduce

`pnpm run dev`

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Ahh APIs are not dev friendly 🙈 you can point to prod or testnet in the meanwhile.

Or you can bring your own API keys which you can find in .env file

**Comment by iPaulPro** [comment]
I tried running testnet but still have the same issue. Do you know which key, specially, causes this? It used to run with my current .env but not anymore.
