### ISSUE TITLE
Constantly calling Verify on the Lens API

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#5032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/heyxyz/hey/assets/354227/050ff86d-98db-4fcc-b274-7068b4b1aea6

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is just to make sure we the authed account's credentials are correct and also used to refresh the tokens automatically.

However this is a temp workaround to make sure we send correct tokens to Hey API for validation, I will find a way to fix this 🙇🏼
