### ISSUE TITLE
Strange frame behavior

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#5149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Strange flickering and frame changing on scroll

https://github.com/user-attachments/assets/ed09c532-1b62-4aad-8e4e-6a6a054af64e

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by defispartan** [comment]
I've noticed this as well, it's especially noticable on a feed with multiple frames in view at once such as https://hey.xyz/u/nftminterr.

Frames are rendered based on the response from the Hey `oembed` API endpoint, so I think there is an error in [this file](https://github.com/heyxyz/hey/blob/main/apps/web/src/components/Shared/Oembed/Frames/index.tsx) or within the frame store that is causing the embed to return stale data.
