### ISSUE TITLE
Polls always show voted state

### ISSUE THREAD

**Issue by iPaulPro** [heyxyz/hey#5350]
Anytime I see a poll it appears to show that I have already voted on it, even when I have not. Eg:

<img src="https://github.com/user-attachments/assets/e1feea7b-a15b-44ee-91bf-6162b852d1f4" width=480>

I have not voted on [this poll](https://hey.xyz/posts/0x022ccf-0x3e-DA-790da5a9).

**Comment by bigint** [comment]
Let me check and fix 🙇🏼
