### ISSUE TITLE
[ENG-67] Able to explore users

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#541]
null

<sub>[ENG-67](https://linear.app/heyxyz/issue/ENG-67/able-to-explore-users)</sub>

**Comment by cit666** [comment]
Good

**Comment by w0xter** [comment]
Where can I read more about this issue??, I mean currently you can search users on the search bar, are we talking about a discover feed where you can see profiles instead of posts?

**Comment by nicefacer** [comment]
Can you give more details for this task, I like to take it
