### ISSUE TITLE
Add support for alt text on user attachments for improved a11y

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#5430]

**Comment by r0ld3x** [comment]
alt text on home page images?

**Comment by bigint** [comment]
@r0ld3x alt text on user attachments 🙇🏼

**Comment by goffxnca** [comment]
Hi @r0ld3x, did you already started working on this? incase I might if you aren't.

**Comment by r0ld3x** [comment]
> Hi @r0ld3x, did you already started working on this? incase I might if you aren't.

No I didn't start yet you can take this
