### ISSUE TITLE
[ENG-65] Add skeleton loader for loading images

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#59]
null

<sub>[ENG-65](https://linear.app/heyxyz/issue/ENG-65/add-skeleton-loader-for-loading-images)</sub>

**Comment by foolo** [comment]
@bigint What images (in what page or location) does this refer to? For images in posts, there is a grey background before the images has loaded, which looks OK in my opinion. On the NFT page for a user, there's already a skeleton loader. Is there some other place that needs skeleton loader?

**Comment by richardgreg** [comment]
Hi @bigint please assign me to this task :)

**Comment by bigint** [comment]
@richardgreg assigned 🚀

**Comment by Creed1732** [comment]
@bigint please assign me this task for submission. i was the one that did it on dework and you said i should have a PR repo for re submission.

**Comment by richardgreg** [comment]
@Creed1732 Sure, go ahead and work on it. Though it seems lenster already has the skeleton loader feature. Or am I missing something?

**Comment by Creed1732** [comment]
yea, they have that already...but not for the images...btw are you a moderator?....
just asking...

**Comment by richardgreg** [comment]
No, a contributor

**Comment by Creed1732** [comment]
I already did the task, just waiting to get assigned so i'll make submissions @richardgreg

**Comment by bigint** [comment]
@Creed1732 assigned

**Comment by Creed1732** [comment]
@bigint check submission

**Comment by bigint** [comment]
@Creed1732 where is the PR?

**Comment by brymut** [comment]
Hi @bigint, had a quick look at this. Which images would we be trying to add a loading shimmer to? As far as I can see, in publications, the `PublicationPageShimmer` would cover the whole post including the image in the post and the rest seem to be covered as mentioned here,  https://github.com/lensterxyz/lenster/issues/59#issuecomment-1347188752. Could you please clarify on how this would be handled?

**Comment by Creed1732** [comment]
I could not find #59 where i was to compare branches

**Comment by Sahil-B07** [comment]
is the issue open rn?
