### ISSUE TITLE
Think about allowance amount and try avoiding infinity IMO

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#64]
null

<sub>[ENG-66](https://linear.app/heyxyz/issue/ENG-66/think-about-allowance-amount-and-try-avoiding-infinity-imo)</sub>

**Comment by foolo** [comment]
@bigint Some thoughts about the UX: Do we want 1. the user to be able to select a custom max value? Or 2. a hardcoded max value in MATIC?
It seems like 1 would be the most obvious choice, but there may be some drawbacks that I have not thought about.
